server:
   port: 8080

logging:
   level:
      root: INFO
      org.springframework.web: TRACE
      org.springframework.security: TRACE
      org.springframework.security.saml: TRACE
      org.opensaml.xmlsec: TRACE

spring:
   security:
      saml2:
         relyingparty:
            registration:
               carsonline:
                  signing:
                     credentials: 
                        # These credentials are used when signing requests
                        # Create your own private.key and certificate
                        - private-key-location: "classpath:credentials/private.key"
                          certificate-location: "classpath:credentials/certificate.crt"
                  decryption:
                     credentials: 
                        # These credentials are used when decrypting Okta Responses
                        - private-key-location: "classpath:credentials/private.key"
                          certificate-location: "classpath:credentials/certificate.crt"
                  singlelogout:
                     binding: POST
                     url: "{baseUrl}/logout/saml2/slo"
                  assertingparty: 
                     # Okta IDP Information (Just point to metadata saved locally)
                     # You can also point to Http url of Okta metadata
                     metadata-uri: "classpath:okta-metadata-replace.xml"
